insert into contact (first_name, last_name, birth_date) values ('Alexi', 'Laiho', '1979-04-02');
insert into contact (first_name, last_name, birth_date) values ('John', 'Frusciante', '1970-03-05');
insert into contact (first_name, last_name, birth_date) values ('Seth', 'Putnam', '1968-05-15');
insert into contact (first_name, last_name, birth_date) values ('Thom', 'Yorke', '1968-10-07');
insert into contact (first_name, last_name, birth_date) values ('Jared', 'Leto', '1971-12-26');
insert into contact (first_name, last_name, birth_date) values ('Matt', 'Bellamy', '1978-06-09');
insert into contact (first_name, last_name, birth_date) values ('Till', 'Lindemann', '1963-01-04');
insert into contact (first_name, last_name, birth_date) values ('James', 'Hetfield', '1963-08-08');
insert into contact (first_name, last_name, birth_date) values ('John', 'Lennon', '1940-10-09');
insert into contact (first_name, last_name, birth_date) values ('Dani', 'Filth', '1973-07-25');
insert into contact (first_name, last_name, birth_date) values ('George', 'Fisher', '1969-07-08');
insert into contact (first_name, last_name, birth_date) values ('Brent', 'Smith', '1978-01-10');
insert into contact (first_name, last_name, birth_date) values ('Billie', 'Armstrong ', '1972-02-17');